const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'src', 'app', 'projects', 'ProjectsClient.tsx');
let content = fs.readFileSync(filePath, 'utf8');

const translations = [
  ["Renovação completa do imóvel", "Full Home Renovation"],
  ["Este projeto representa uma transformação residencial completa", "This project represents a complete residential transformation"],
  ["desde a fundação, executada com precisão", "from the foundation, executed with precision"],
  ["Cada fase da renovação", "Every phase of the renovation"],
  ["foi meticulosamente gerenciada", "was meticulously managed"],
  ["proporcionando uma integração perfeita", "providing seamless integration"],
  ["entre as melhorias estruturais e os acabamentos interiores refinados", "between structural improvements and refined interior finishes"],
  ["O escopo incluiu a modernização completa", "The scope included complete modernization"],
  ["dos sistemas hidráulico, elétrico e mecânico", "of plumbing, electrical, and mechanical systems"],
  ["garantindo desempenho ideal", "ensuring optimal performance"],
  ["eficiência e conformidade com as normas de construção modernas", "efficiency and compliance with modern building codes"],
  ["As melhorias estruturais foram complementadas", "Structural improvements were complemented"],
  ["por reparos no telhado, instalação de novas paredes de drywall", "by roof repairs, installation of new drywall"],
  ["novas janelas e portas resistentes a impactos em toda a casa", "new impact-resistant windows and doors throughout the house"],
  ["uma nova porta de entrada de luxo também resistente a impactos", "a new luxury impact-resistant entry door"],
  ["e acabamentos detalhados em toda a propriedade", "and detailed finishes throughout the property"],
  ["O interior foi repensado com marcenaria e armários sob medida", "The interior was reimagined with custom millwork and cabinetry"],
  ["instalação de pisos de alta qualidade e materiais cuidadosamente selecionados", "installation of high-quality flooring and carefully selected materials"],
  ["que aprimoram tanto a durabilidade quanto o valor estético", "that enhance both durability and aesthetic value"],
  ["A cozinha e a sala de estar foram transformadas", "The kitchen and living room were transformed"],
  ["em um layout coeso e de conceito aberto", "into a cohesive, open-concept layout"],
  ["com elementos personalizados e acabamento de alto padrão", "with custom elements and high-end finishes"],
  ["As melhorias externas incluíram um pátio ampliado", "Exterior improvements included an expanded patio"],
  ["projetado para ampliar a experiência de vida ao ar livre", "designed to enhance the outdoor living experience"],
  ["e criar uma transição perfeita entre os ambientes internos e externos", "and create a seamless transition between indoor and outdoor spaces"],
  ["Cada detalhe, da infraestrutura aos acabamentos finais", "Every detail, from infrastructure to final finishes"],
  ["foi executado para entregar uma residência pronta para morar", "was executed to deliver a move-in ready residence"],
  ["que reflete sofisticação, funcionalidade e valor a longo prazo", "that reflects sophistication, functionality, and long-term value"],
  ["Renovação completa de imóvel moderno", "Modern Full Home Renovation"],
  ["Este projeto representa uma transformação residencial de luxo completa", "This project represents a complete luxury residential transformation"],
  ["construída do zero com foco em integridade estrutural", "built from the ground up with a focus on structural integrity"],
  ["design sofisticado e acabamento excepcional", "sophisticated design, and exceptional craftsmanship"],
  ["Da fundação aos detalhes arquitetônicos finais", "From the foundation to the final architectural details"],
  ["cada fase foi cuidadosamente planejada", "each phase was carefully planned"],
  ["e executada profissionalmente para entregar", "and professionally executed to deliver"],
  ["um resultado impecável e de alto padrão", "a flawless, high-end result"],
  ["O escopo incluiu preparação completa do terreno", "The scope included complete site preparation"],
  ["construção da fundação, instalação da piscina", "foundation construction, pool installation"],
  ["áreas de deck personalizadas", "custom deck areas"],
  ["sistemas hidráulicos, elétricos e mecânicos", "plumbing, electrical, and mechanical systems"],
  ["além de melhorias estruturais em toda a propriedade", "as well as structural improvements throughout the property"],
  ["Cada componente foi projetado para integrar", "Each component was designed to integrate"],
  ["funcionalidade, durabilidade e luxo moderno", "functionality, durability, and modern luxury"],
  ["Os espaços internos e externos foram cuidadosamente desenvolvidos", "Indoor and outdoor spaces were carefully developed"],
  ["para criar uma experiência coesa entre interior e exterior", "to create a cohesive indoor-outdoor experience"],
  ["combinando materiais de primeira linha", "combining top-tier materials"],
  ["acabamentos refinados e detalhes personalizados", "refined finishes, and custom details"],
  ["adaptados à arquitetura e ao estilo de vida da propriedade", "tailored to the property's architecture and lifestyle"],
  ["As áreas de convivência ao ar livre", "Outdoor living areas"],
  ["a piscina e os espaços de entretenimento", "the pool, and entertainment spaces"],
  ["foram projetados para aumentar o conforto", "were designed to increase comfort"],
  ["a elegância e o valor da propriedade a longo prazo", "elegance, and the long-term value of the property"],
  ["mantendo uma estética sofisticada e atemporal", "maintaining a sophisticated and timeless aesthetic"],
  ["Da infraestrutura e construção aos acabamentos de luxo", "From infrastructure and construction to luxury finishes"],
  ["e ao design das áreas externas", "and exterior design"],
  ["este projeto foi concluído com precisão", "this project was completed with precision"],
  ["coordenação e atenção a cada detalhe", "coordination, and attention to every detail"],
  ["entregando uma residência pronta para morar", "delivering a move-in ready residence"],
  ["construída para beleza e desempenho", "built for beauty and performance"],
  ["Pisos Premium, Reforma de Cozinhas e Banheiros", "Premium Flooring, Kitchen & Bathroom Remodeling"],
  ["Localizado em Fort Lauderdale, este projeto teve como foco", "Located in Fort Lauderdale, this project focused on"],
  ["a modernização dos pisos e banheiros", "modernizing floors and bathrooms"],
  ["resultando em um interior mais sofisticado e funcional", "resulting in a more sophisticated and functional interior"],
  ["O escopo incluiu a instalação de pisos de alta qualidade", "The scope included high-quality flooring installation"],
  ["e a reforma completa dos banheiros", "and complete bathroom remodeling"],
  ["utilizando materiais de primeira linha e mão de obra especializada", "using premium materials and specialized craftsmanship"],
  ["O resultado é um espaço moderno e elegante", "The result is a modern and elegant space"],
  ["projetado para conforto, durabilidade e luxo no dia a dia", "designed for comfort, durability, and everyday luxury"],
  ["Reforma completa do interior", "Complete interior remodel"],
  ["incluindo demolição, atualizações estruturais", "including demolition, structural updates"],
  ["e reconstrução total de todos os espaços habitáveis", "and total reconstruction of all living spaces"],
  ["O escopo abrange cozinhas, banheiros e pisos", "The scope covers kitchens, bathrooms, and flooring"],
  ["executados com coordenação precisa", "executed with precise coordination"],
  ["acabamento de alta qualidade e entrega totalmente pronta para morar", "high-quality craftsmanship, and fully move-in ready delivery"],
  ["Transformação de Apartamento de Luxo", "Luxury Apartment Transformation"],
  ["Este projeto apresenta uma transformação completa do interior", "This project features a complete interior transformation"],
  ["de um apartamento residencial", "of a residential apartment"],
  ["executada com foco em precisão, eficiência e design sofisticado", "executed with a focus on precision, efficiency, and sophisticated design"],
  ["Cada aspecto da reforma foi cuidadosamente coordenado", "Every aspect of the remodel was carefully coordinated"],
  ["para proporcionar um ambiente moderno e refinado", "to provide a modern and refined environment"],
  ["com funcionalidade impecável", "with impeccable functionality"],
  ["A estrutura interna foi aprimorada com a instalação de novas placas de gesso", "The internal structure was enhanced with the installation of new drywall"],
  ["acabamentos detalhados e preparação impecável das superfícies em todo o espaço", "detailed finishes, and flawless surface preparation throughout the space"],
  ["O apartamento foi repensado com armários planejados", "The apartment was reimagined with custom cabinetry"],
  ["marcenaria e pisos de alta qualidade", "high-quality millwork and flooring"],
  ["criando uma estética coesa e sofisticada", "creating a cohesive and sophisticated aesthetic"],
  ["A cozinha e a sala de estar foram redesenhadas em um layout aberto e integrado", "The kitchen and living room were redesigned into an open and integrated layout"],
  ["maximizando espaço, luz e fluidez", "maximizing space, light, and flow"],
  ["ao mesmo tempo que incorporam materiais de primeira linha", "while incorporating top-tier materials"],
  ["e detalhes personalizados", "and custom details"],
  ["Os banheiros e as salas de estar foram modernizados", "Bathrooms and living rooms were modernized"],
  ["com acabamentos contemporâneos", "with contemporary finishes"],
  ["oferecendo conforto e durabilidade", "offering comfort and durability"],
  ["Cada elemento — da infraestrutura aos detalhes finais —", "Every element — from infrastructure to final details —"],
  ["foi executado com um compromisso com a qualidade artesanal e o design atemporal", "was executed with a commitment to craftsmanship and timeless design"],
  ["O resultado é um apartamento totalmente reformado", "The result is a fully renovated apartment"],
  ["pronto para morar, que combina elegância, funcionalidade e valor a longo prazo", "ready to move in, combining elegance, functionality, and long-term value"],
  ["Instalação de Revestimento de Porcelanato em Deck de Piscina", "Porcelain Tile Installation on Pool Deck"],
  ["Preparação da área do deck da piscina", "Preparation of the pool deck area"],
  ["incluindo nivelamento e base", "including leveling and base"],
  ["seguida da instalação precisa de azulejos", "followed by the precise installation of tiles"],
  ["ao redor do perímetro da piscina", "around the pool perimeter"],
  ["O serviço inclui inclinação adequada para drenagem", "The service includes proper grading for drainage"],
  ["alinhamento preciso, rejuntamento", "precise alignment, grouting"],
  ["acabamento das bordas e instalação detalhada do revestimento", "edge finishing, and detailed tile installation"],
  ["para um resultado final impecável e refinado", "for a flawless and refined final result"],
  ["Pérgolas e cercas de luxo no sul da Flórida", "Luxury Pergolas and Fences in South Florida"],
  ["projetamos e construímos pérgolas e cercas de luxo personalizadas", "we design and build custom luxury pergolas and fences"],
  ["que combinam elegância, privacidade, durabilidade e acabamento excepcional", "that combine elegance, privacy, durability, and exceptional craftsmanship"],
  ["Atendemos com orgulho comunidades residenciais de alto padrão", "We proudly serve high-end residential communities"],
  ["incluindo Naples, Bonita Springs, Parkland", "including Naples, Bonita Springs, Parkland"],
  ["Lighthouse Point, Palm City, Boca Raton", "Lighthouse Point, Palm City, Boca Raton"],
  ["Fort Lauderdale e arredores no sul da Flórida", "Fort Lauderdale, and surrounding areas in South Florida"],
  ["De espaços modernos de convivência ao ar livre a cercas arquitetônicas personalizadas", "From modern outdoor living spaces to custom architectural fences"],
  ["adaptamos cada projeto com materiais de primeira linha", "we tailor each project with top-tier materials"],
  ["design atemporal e atenção a cada detalhe", "timeless design, and attention to every detail"],
  ["Projetos de Remodelação de Cozinhas de Luxo", "Luxury Kitchen Remodeling Projects"],
  ["A cozinha é o coração da casa", "The kitchen is the heart of the home"],
  ["criamos espaços que combinam beleza, funcionalidade e valor duradouro com perfeição", "we create spaces that perfectly combine beauty, functionality, and lasting value"],
  ["Seja qual for a sua visão", "Whatever your vision"],
  ["uma cozinha branca atemporal, um design aconchegante em carvalho", "a timeless white kitchen, a cozy oak design"],
  ["um layout moderno e elegante, um estilo de transição sofisticado", "a sleek modern layout, a sophisticated transitional style"],
  ["ou uma cozinha de luxo totalmente personalizada", "or a fully custom luxury kitchen"],
  ["nossa equipe dá vida ao seu projeto", "our team brings your project to life"],
  ["com excepcional habilidade e atenção aos detalhes", "with exceptional skill and attention to detail"],
  ["De armários planejados e bancadas de alta qualidade", "From custom cabinetry and high-quality countertops"],
  ["a soluções inovadoras de armazenamento, iluminação, pisos", "to innovative storage solutions, lighting, flooring"],
  ["e transformações completas do layout", "and complete layout transformations"],
  ["cada elemento é cuidadosamente selecionado", "each element is carefully selected"],
  ["para aprimorar tanto a estética quanto o dia a dia", "to enhance both aesthetics and everyday living"],
  ["Nosso objetivo é criar uma cozinha", "Our goal is to create a kitchen"],
  ["que reflita seu estilo pessoal", "that reflects your personal style"],
  ["proporcionando o conforto, a funcionalidade e a elegância que sua casa merece", "providing the comfort, functionality, and elegance your home deserves"],
  ["Com um compromisso com a qualidade e a excelência", "With a commitment to quality and excellence"],
  ["transformamos cozinhas comuns em espaços extraordinários", "we transform ordinary kitchens into extraordinary spaces"],
  ["projetados para serem apreciados por muitos anos", "designed to be enjoyed for many years"],
  ["Projetos de reforma de banheiros de luxo", "Luxury Bathroom Remodeling Projects"],
  ["Transforme seu banheiro em um refúgio de luxo privativo", "Transform your bathroom into a private luxury retreat"],
  ["com projetos personalizados que combinam elegância", "with custom projects that combine elegance"],
  ["conforto e funcionalidade", "comfort, and functionality"],
  ["somos especialistas em reformas de banheiros de alto padrão", "we specialize in high-end bathroom remodeling"],
  ["com chuveiros de entrada direta, banheiras de imersão", "with zero-entry showers, soaking tubs"],
  ["bancadas personalizadas, azulejos premium, pedras naturais", "custom countertops, premium tiles, natural stone"],
  ["iluminação de luxo, boxes de vidro sem moldura e acessórios de design", "luxury lighting, frameless glass enclosures, and designer fixtures"],
  ["Seja qual for o seu estilo – moderno, contemporâneo ou clássico –", "Whatever your style – modern, contemporary, or classic –"],
  ["criamos banheiros belíssimos, inspirados em spas", "we create beautiful, spa-inspired bathrooms"],
  ["com acabamento excepcional e atenção a cada detalhe", "with exceptional craftsmanship and attention to every detail"],
  ["Móveis sob medida, painéis de parede e design de interiores", "Custom Furniture, Wall Panels & Interior Design"],
  ["Transforme seu espaço com móveis sob medida", "Transform your space with custom furniture"],
  ["painéis de parede decorativos e soluções de design de interiores personalizadas", "decorative wall panels, and custom interior design solutions"],
  ["que combinam luxo, funcionalidade e acabamento excepcional", "that combine luxury, functionality, and exceptional craftsmanship"],
  ["projetamos e construímos centros de entretenimento", "we design and build entertainment centers"],
  ["painéis multimídia, armários embutidos, paredes de destaque", "media panels, built-in cabinets, accent walls"],
  ["painéis ripados de madeira, painéis canelados", "wood slat panels, fluted panels"],
  ["prateleiras personalizadas e marcenaria arquitetônica sob medida para a sua visão", "custom shelving, and architectural millwork tailored to your vision"],
  ["Cada detalhe é cuidadosamente elaborado para criar interiores elegantes e atemporais", "Every detail is carefully crafted to create elegant and timeless interiors"],
  ["que valorizam tanto espaços residenciais quanto comerciais", "that enhance both residential and commercial spaces"],
  ["Todas", "All"],
  ["Renovações Completas", "Full Renovations"],
  ["Cozinhas e Banheiros", "Kitchens & Bathrooms"],
  ["Exteriores", "Outdoor Spaces"],
  ["Marcenaria e Interiores", "Custom Millwork"],
  ["Nenhum projeto encontrado nesta categoria.", "No projects found in this category."],
  ["Galeria de Inspirações", "Inspiration Gallery"],
  ["Explore centenas de fotos exclusivas dos nossos projetos.", "Explore hundreds of exclusive photos of our projects."],
  ["Inspiração", "Inspiration"],
  ["Carregar Mais Fotos", "Load More Photos"],
  ["Mostrando", "Showing"],
  ["fotos", "photos"],
  ["\\bde\\b", "of"],
  ["A excelência está sempre em construção.", "Excellence is always under construction."],
  ["Nossa equipe dá vida a novos projetos de luxo todos os dias.", "Our team brings new luxury projects to life every day."],
  ["Mais espaços belamente concebidos e transformações inspiradoras", "More beautifully designed spaces and inspiring transformations"],
  ["serão adicionados em breve.", "will be added soon."],
  ["Fique atento, pois continuaremos a construir interiores excepcionais", "Stay tuned as we continue to build exceptional interiors"],
  ["projetados para superar expectativas.", "designed to exceed expectations."],
  ["Em breve", "Coming Soon"],
  ["Pronto para começar seu projeto?", "Ready to start your project?"],
  ["Se você está planejando uma reforma, uma nova construção", "If you are planning a remodel, new construction"],
  ["ou precisa de um empreiteiro geral confiável em Pompano Beach", "or need a reliable general contractor in Pompano Beach"],
  ["ou em qualquer lugar no sul da Flórida", "or anywhere in South Florida"],
  ["a Cavare Interiors está pronta para dar vida à sua visão.", "Cavare Interiors is ready to bring your vision to life."],
  ["Solicite um orçamento hoje mesmo!", "Request a quote today!"],
  ["Ligue para 754-315-7373", "Call 754-315-7373"],
  ["PROJETOS DA CAVARE", "CAVARE PROJECTS"],
  ["Nosso trabalho:", "Our work:"],
  ["Projetos reais. Resultados refinados.", "Real projects. Refined results."],
  ["A Cavare Interiors apresenta um portfólio selecionado de projetos concluídos", "Cavare Interiors presents a curated portfolio of completed projects"],
  ["no sul e sudoeste da Flórida, incluindo Naples", "in South and Southwest Florida, including Naples"],
  ["Cape Coral, Pompano Beach, Fort Lauderdale, Boca Raton, Palm Beach", "Cape Coral, Pompano Beach, Fort Lauderdale, Boca Raton, Palm Beach"],
  ["e comunidades de luxo vizinhas.", "and neighboring luxury communities."],
  ["Projetos", "Projects"],
  ["foto", "photo"]
];

for (const [pt, en] of translations) {
  content = content.replace(new RegExp(pt, 'g'), en);
}

fs.writeFileSync(filePath, content, 'utf8');
console.log('ProjectsClient.tsx translated successfully without breaking code');
